_:
  age-public-keys:
    - &deploy age15uc7fh9ypkxwnmwu9pzekrju4jv5atvcqklyacxv0325625gvsvqp8fvdl
    - &aster-void age1j647p0v0w4yjae97agk709smzjgyyl8ft4jp35hyh2ffeaj9wg9qfu3pe7

creation_rules:
  - path_regex: bots/auto-moderator/sops2.env
    age:
      - *deploy
  - path_regex: bots/auto-moderator/*
    age:
      - *deploy
      - *aster-void
