runner:
  timezone: Asia/Tokyo
  env_file: ~/run/discord-bots/runner.env
  env:
    MISE_TRUSTED_CONFIG_PATHS: ~/.cache/rollcron
  webhook:
    - type: discord
      url: $DISCORD_WEBHOOK_URL

jobs:
  auto-moderator:
    schedule: noon
    run: bots/auto-moderator/run.sh
    log: ~/run/discord-bots/auto-moderator/log

  gsc-report:
    schedule: "7am every Sunday"
    run: bots/gsc-report/run.sh
    env_file: ~/run/discord-bots/gsc-report/env
    log: ~/run/discord-bots/gsc-report/log

  asakatsu-bot-ask:
    schedule: 7PM
    run: bots/asakatsu-bot/run.sh ask
    env_file: ~/run/discord-bots/asakatsu-bot/env
    log: ~/run/discord-bots/asakatsu-bot/log

  asakatsu-bot-check:
    schedule: 8AM
    run: bots/asakatsu-bot/run.sh check
    env_file: ~/run/discord-bots/asakatsu-bot/env
    log: ~/run/discord-bots/asakatsu-bot/log

  # joji-bot:
  #   schedule: "7pm"
  #   run: bots/joji-bot/run.sh
  #   env_file: ~/run/discord-bots/joji-bot/env
  #   log: ~/run/discord-bots/joji-bot/log

